language: android
before_install:
 - chmod +x gradlew
android:
  components:
    - build-tools-27.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-27
    - sys-img-armeabi-v7a-android-27
    - sys-img-x86-android-27
